version = 330
profile = "core"

[layout]
aPos = "vec3"


[uniform]
projview = "mat4"
color = "vec4"

[fragment]
output = { out_color = "vec4" }
source = '''
        out_color = color;
'''

[vertex]
output = { }

source = '''
    gl_Position = projview * vec4(aPos, 1.0);
'''