version = 330
profile = "core"

[layout]
aPos = "vec2"
aTexCoords = "vec2"

[uniform]
screenTexture = "sampler2D "

[fragment]
output = { FragColor = "vec4" }
source = '''
    FragColor = texture(screenTexture, TexCoords).rgba;
    //FragColor = vec4(col, 1.0);
   //FragColor = vec4(1.0,0.0,0.0,1.0);
'''

[vertex]
output = { TexCoords = "vec2" }

source = '''
     TexCoords = aTexCoords;
     gl_Position = vec4(aPos,0.0,1.0);
'''