version = 330
profile = "core"

[layout]
aPos = "vec3"
aTex = "vec2"
aNormal = "vec3"

[uniform]
model = "mat4"
projview = "mat4"
tex0 = "sampler2D"

[fragment]
output = { out_color = "vec4" }
source = '''
    out_color = texture(tex0,tex) * vec4(light,light,light,1.0);
    if(out_color.w == 0) {
        discard;
    }
'''

[vertex]
output = { tex = "vec2", normal = "vec3", light = "float" }

source = '''
    gl_Position = projview * model * vec4(aPos, 1.0);
    tex = aTex;

    float env = 0.3f;
    float dirEnv = 1-env;

    vec3 dir = normalize(vec3(0.2,0.4,0.6));
    float dirLight = (dot(aNormal,dir) +1.0 ) * 0.5;
    light = env + dirLight * dirEnv;
    normal = aNormal;
'''